import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const calSans = localFont({
  src: "../public/fonts/CalSans-Regular.woff2"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
      </head>
      <body
        className={`${calSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
