import { Montserrat } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

// Initialize Montserrat font with specific options (optional)
const montserrat = Montserrat({ 
  subsets: ['latin'], 
  weights: [400, 700]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
